theme: jekyll-theme-dinky
title: SL1 and BL4 Guidelines
description: A comprehensive and community-supported repository on how the Dark Souls Discord server manages SL1/BL4 runs and their numerous variations.
